development:
  password: 0d1e460e75a9e993dbf8e9a3f9a464a0
  theme_id: "74031038519"
  store: https://mcsquares-dev.myshopify.com
  ignore_files:
  - config/settings_data.json
  - theme.lock

production:
  password: d87ce454d3a1796df16838923197c5b4
  theme_id: "76938444887"
  store: https://mcsquares.myshopify.com
  ignore_files:
  - config/settings_data.json
  - theme.lock